---
- hosts: all
  gather_facts: no
  remote_user: pirate
  become: yes
  become_method: sudo

  tasks:
  - name: Stop All Docker Containers
    shell: 'docker stop $(docker ps -a -q)'

  - name: Delete All Docker Containers
    shell: 'docker rm $(docker ps -a -q)'
