version: '2'
services:
    elk:
        image: radcortez/elk
        container_name: elk
        ports:
            - 5601:5601
            - 9200:9200
            - 5044:5044
            - 12201:12201/udp
        volumes:
          - ./elk:/etc/logstash/conf.d/
