version: '2'
services:
    angular-app:
        image: baking/angular:default
        ports:
            - 8080:80
        depends_on:
          - book-api
          - number-api
    book-api:
        image: baking/book-api:default
        ports:
            - 8081:8081
        depends_on:
          - number-api
    number-api:
        image: baking/number-api:default
        ports:
            - 8084:8084
