---
- hosts: databases
  strategy: free
  gather_facts: no
  remote_user: pirate
  become: yes
  become_method: sudo

  tasks:
  - name: Consul
    docker_container:
      name: consul
      image: radcortez/consul-rpi
      state: started
      restart: yes
      pull: true
      ports:
        - 8300:8300
        - 8500:8500
        - 8600:8600
      log_driver: gelf
      log_options:
        gelf-address: udp://elk:12201
    when: inventory_hostname == "pi-grom-database"

  - name: Tribestream Access Gateway
    docker_container:
      name: tag
      image: tomitribe/tribestream-api-gateway-rpi
      state: started
      restart: yes
      recreate: yes
      pull: true
      ports:
        - 9000:8080
      env:
        LICENSE: 'accept'
        CASSANDRA_EMBEDDED: 'true'
        BOOK_API_HOST: http://pi-grom-load-balancer
        BOOK_API_PORT: 8081
    when: inventory_hostname == "pi-thrall-database"

  - name: Tribestream Access Gateway Config
    docker_container:
      name: tag-config
      image: docker-registry:5000/baking/tag-config:rpi
      state: started
      restart: yes
      pull: true
      env:
        TAG_HOST: http://pi-thrall-database
        TAG_PORT: 9000
        CONSUL_HOST: http://pi-grom-database
        CONSUL_PORT: 8500
    when: inventory_hostname == "pi-grom-database"
