---
- hosts: clients
  gather_facts: no
  remote_user: pirate
  become: yes
  become_method: sudo

  tasks:
  - name: Create external directory for Nginx configuration
    file: path=/usr/local/share/nginx/ state=directory
    when: inventory_hostname == "pi-client-01"

  - name: Copy Nginx configuration
    copy:
      src: nginx/default
      dest: /usr/local/share/nginx/default
    when: inventory_hostname == "pi-client-01"

  - name: Deploy Angular Client
    docker_container:
      name: angular
      image: docker-registry:5000/baking/angular:rpi
      state: started
      restart: yes
      pull: true
      ports:
       - "8080:80"
      volumes: /usr/local/share/nginx/default:/etc/nginx/sites-enabled/default:ro

    when: inventory_hostname == "pi-client-01"

  - name: Deploy Simulator
    docker_container:
      name: simulator
      image: docker-registry:5000/baking/simulator:rpi
      state: started
      restart: yes
      pull: true
      env:
        BOOK_TARGET_URL: http://pi-thrall-database:9000
        BOOK_CONTEXT_ROOT: http://pi-thrall-database:9000
        SIMULATOR_HOST: http://{{inventory_hostname}}
        SIMULATOR_PORT: 9180
        CONSUL_HOST: http://pi-grom-database
        CONSUL_POST: 8500
      ports:
       - "9180:9180"
      log_driver: gelf
      log_options:
        gelf-address: udp://elk:12201
    when: (inventory_hostname == "pi-client-02") or (inventory_hostname == "pi-client-03")
